# app/config/security.yml

security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        Project\UserBundle\Entity\User:
            algorithm:           sha512
            encode_as_base64:    true
            iterations:          5000

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        main_login:
            pattern:    ^/login$
            anonymous:  true
        main_register:
            pattern:    ^/register/$
            anonymous:  true
        main_home:
            pattern:    ^/home$
            anonymous:  true
            context:    my_context
        application_css:
            pattern:    ^/css
            anonymous:  true
            context:    my_context
        application_js:
            pattern:    ^/js
            anonymous:  true
            context:    my_context
        main:
            pattern:    ^/
            anonymous:  false
            provider:   main
            context:    my_context
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /home
            logout:
                path:   fos_user_security_logout
                target: /home
            remember_me:
                key:      %secret%
                lifetime: 2232000

    access_control:
       - { path: ^/admin, roles: ROLE_SUPER_ADMIN }