<?php

namespace Project\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandStatusRepository extends EntityRepository
{
}
