<?php

namespace Project\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends EntityRepository
{

    Public function getCommandForProductor($user)
    {

        $qb = $this->createQueryBuilder('c');

        //création de l'expression OR
        $orModule = $qb->expr()->orx();
        $orModule->add($qb->expr()->eq('c.userProduct', ':user'));
        $orModule->add($qb->expr()->isNull('c.userProduct'));

        //Ajout de l'expression à la requête
        $qb->Where($orModule)
            ->setParameter('user', $user);

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

}
