<?php

namespace Project\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Project\UserBundle\Entity\User;

/**
 * contactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{

}
