services:
    oc_platform.antispam:
        class: OC\platformBundle\Antispam\OCAntispam
        arguments: [@mailer,%locale%,50]
services:
    oc_platform.doctrine.notification:
            class: OC\PlatformBundle\DoctrineListener\ApplicationNotification
            arguments: [@mailer]
            tags:
                - { name: doctrine.event_listener, event: postPersist }