project_platform_homepage:
    path:     /home
    defaults: { _controller: ProjectPlatformBundle:Platform:index }

project_platform_adminpage:
    path:     /admin
    defaults: { _controller: ProjectPlatformBundle:Platform:admin }

project_platform_productionpage:
    path:     /production
    defaults: { _controller: ProjectPlatformBundle:Platform:production }

project_platform_contactpage:
    path:     /contact
    defaults: { _controller: ProjectPlatformBundle:Platform:contact }

project_platform_commandpage:
    path:     /commande
    defaults: { _controller: ProjectPlatformBundle:Platform:command }

project_platform_viewContact:
    path:     /contact/{uid}
    defaults: { _controller: ProjectPlatformBundle:Platform:viewContact }