project_platform_homepage:
    path:     /home
    defaults: { _controller: ProjectPlatformBundle:Platform:index }

project_platform_adminpage:
    path:     /admin
    defaults: { _controller: ProjectPlatformBundle:Platform:admin }

project_platform_contactpage:
    path:     /contact
    defaults: { _controller: ProjectPlatformBundle:Platform:contact }

project_platform_sendpage:
    path:     /envoie
    defaults: { _controller: ProjectPlatformBundle:Platform:send }